# Generated by Django 5.2.7 on 2025-10-25 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, unique=True, verbose_name='用户名')),
                ('password', models.CharField(max_length=128, null=True, verbose_name='密码')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='邮箱')),
                ('avatar', models.CharField(max_length=200, verbose_name='用户头像')),
                ('age', models.CharField(max_length=20, verbose_name='年龄')),
                ('gender', models.CharField(max_length=10, verbose_name='性别')),
                ('height', models.CharField(max_length=10, verbose_name='身高')),
                ('weight', models.CharField(max_length=10, verbose_name='体重')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
